default_platform(:android)

platform :android do

  desc "Run unit tests"
  lane :test do
    gradle(task: "test")
  end


  desc "Build release APK"
  lane :build do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end


  desc "Deploy to Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end


  desc "Build APK and upload to Firebase App Distribution"
  lane :firebase do

    gradle(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      apk_path: "app/build/outputs/apk/release/app-release.apk",
      groups: "tester",
      release_notes: "CI build #{Time.now}"
    )

  end
end