name: Android Firebase Distribution

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: test_fast_lane

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      # Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # Install Fastlane plugins
      - name: Install Fastlane plugins
        run: |
          cd android
          bundle install

      # Run fastlane
      - name: Run Fastlane
        run: |
          cd android
          bundle exec fastlane firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          NODE_ENV: production